[package]
name = "worker"
version = "0.0.9"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]
license = "Apache-2.0"
description = "A Rust SDK for writing Cloudflare Workers."
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
chrono = { version = "0.4.19", default-features = false, features = [
    "wasmbind",
] }
chrono-tz = { version = "0.6.1", default-features = false }
futures = "0.3.21"
http = "0.2.6"
js-sys = "0.3.57"
matchit = "0.4.6"
mime_guess = "2.0.4"
pin-project = "1.0.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
url = "2.2.2"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
wasm-streams = "0.2.2"
web-sys = "0.3.57"
worker-kv = "0.5.1"
worker-macros = { path = "../worker-macros", version = "0.0.4" }
worker-sys = { path = "../worker-sys", version = "0.0.4" }
